### PR TITLE
DRAFT - Unity Mod Manager compability 

### PR DESCRIPTION
**Pull request by Zemogiter**
Hello. I'm trying to update this mod to work with Unity Mod Manager (https://www.nexusmods.com/planetbase/mods/43), which is the only mod loading solution that I have managed to get to work. Currently the `Init()` method returns this error:
```
[StorageGuru] Version '2.0.2.0'. Loading.

Non platform assembly: C:\Program Files (x86)\Steam\steamapps\common\Planetbase\Mods\StorageGuru\StorageGuru.dll.28166.cache (this message is harmless)
[StorageGuru] [Error] Error trying to call 'StorageGuru.StorageGuruMod.Init'.

[StorageGuru] [Exception] TargetInvocationException - Exception has been thrown by the target of an invocation.

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object

  at StorageGuru.ContentManager.Init () [0x00000] in <filename unknown>:0 

  at StorageGuru.StorageGuruMod.Init () [0x00000] in <filename unknown>:0 

  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)

  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 

  --- End of inner exception stack trace ---

  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 

  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 

  at UnityModManagerNet.UnityModManager+ModEntry.Invoke (System.String namespaceClassnameMethodname, System.Object& result, System.Object[] param, System.Type[] types) [0x00000] in <filename unknown>:0 

[StorageGuru] Not loaded.

[StorageGuru] Loading time 0.04 s.
```
My current understanding is that the `ContentManager.Init()` is responsible but I don't see why.

I would like some help with the port. Ideally once the port is finished it would be uploaded to Nexus either as an altrernative file in https://www.nexusmods.com/planetbase/mods/13 or a separate mod entirely.

### CODE REVIEW

**Comment by JCoil** [comment]
I haven't had a chance to work out how to mod with UnityModManager yet, so I can't really help.
All I can is that the Patcher (that StorageGuru is written to work with) exposes many fields as public that weren't originally, so at a glance I'd say `StringList.mStrings.Add("tooltip_manage_storage", "Manage Storage");` in ContentManager.Init may be the culprit because mStrings is probably not accessible

**Comment by Zemogiter** [comment]
`mStrings` is shown as private in ILSpy but I use `Krafs.Publicizer` to make the whole `Planetbase` namespace available. Nevertheless, I've commented out that line and now mod loads without errors. I've loaded a pre-existing save, clicked on storage - no storage buttons. Same on a new save. No indication of an error in the log

**Comment by JCoil** [comment]
Well without that line, it may fail to create the buttons because they use that tooltip on construction. As I say, I'm not familiar with the changes required to port to using Unity, so I can't really help... I'll take a look over your fork when I get a chance and see if I can work it out

**Comment by Zemogiter** [comment]
Ok thanks, take your time.

**Comment by JCoil** [comment]
I worked on it a bit in the week - I've got a ported version of CheatTools working on the branch [unitymm-port](https://github.com/JCoil/PlanetbaseMods/tree/unitymm-port) that you might find useful to look at... I started on CheatTools cause it's the simplest, but I reckon the techniques will be similar for the other mods. I pulled some of the helpersout into a helper project that I can hopefully use on the others... edit* Just to be extra confusing, I named the new base class ModBase as well, but it's different to the previous one 😂

**Comment by JCoil** [comment]
Hi I think I've got a version of StorageGuru working against UMM on this [branch](https://github.com/JCoil/PlanetbaseMods/tree/main-unitymodmanager). Feel free to check it out and see if it's working for you

**Comment by Zemogiter** [comment]
It does. Thanks, I had problems with Reflections giving me compile errors. I see that rather than using them you relied on `PlanetbaseModUtilites`. Will try to keep that in mind when it comes to updating other mods.

**Comment by JCoil** [comment]
Yeh PlanetbaseModUtilities is just a small helper library I made to standardize the reflection calls and Harmony/ModEntry setup bits so I could use them across my other mods... I got tired of writing `.GetType().GetField() `etc. over and over! 
I'm not totally happy with all the changes I made to port StorageGuru so I'm going to do some more work to make it a bit more robust

**Pull request closed without merging**
